# See Udp1.yaml for parameter descriptions
/**/*:
  ros__parameters:
    network_interface: "network_bridge::TcpInterface"

    TcpInterface:
      role: "client" # "client" or "server"
      remote_address: "192.168.2.100" # IP of the server
      port: 5000 # Desired port to connect to

    default_rate: 100.0

    default_zstd_level: 3

    publish_stale_data: False

    subscribe_namespace: ""
    publish_namespace: ""
